export enum ApiCode {
  INVALID_REQUEST = "INVALID_REQUEST",
  RETTELL_AGENT_CREATION_FAILED = "RETTELL_AGENT_CREATION_FAILED",
  RETTELL_AGENT_UPDATE_FAILED = "RETTELL_AGENT_UPDATE_FAILED",

  // Plan errors (100-199)
  DOWNGRADE_BLOCKED_AI_AGENTS = "DOWNGRADE_BLOCKED_AI_AGENTS",
  DOWNGRADE_BLOCKED_WHATSAPP_INSTANCES = "DOWNGRADE_BLOCKED_WHATSAPP_INSTANCES",
  DOWNGRADE_BLOCKED_TEAM_MEMBERS = "DOWNGRADE_BLOCKED_TEAM_MEMBERS",

  // Plan errors (100-199)
  PLAN_NOT_FOUND = "PLAN_NOT_FOUND",
  PLAN_LIMIT_EXCEEDED = "PLAN_LIMIT_EXCEEDED",

  // Price errors (100-199)
  PRICE_NOT_FOUND = "PRICE_NOT_FOUND",

  // Session errors (50-59)
  SESSION_NOT_FOUND = "SESSION_NOT_FOUND",
  SESSION_NOT_TEST_SESSION = "SESSION_NOT_TEST_SESSION",
  SESSION_MISSING_SENDER_ID_OR_CHANNEL_ID = "SESSION_MISSING_SENDER_ID_OR_CHANNEL_ID",

  // Validation errors (1000-1099)
  VALIDATION_EMAIL_REQUIRED = "VALIDATION_EMAIL_REQUIRED",
  VALIDATION_EMAIL_INVALID = "VALIDATION_EMAIL_INVALID",
  VALIDATION_PASSWORD_REQUIRED = "VALIDATION_PASSWORD_REQUIRED",
  VALIDATION_PASSWORD_MIN_LENGTH = "VALIDATION_PASSWORD_MIN_LENGTH",
  VALIDATION_PASSWORD_WEAK = "VALIDATION_PASSWORD_WEAK",
  VALIDATION_NAME_REQUIRED = "VALIDATION_NAME_REQUIRED",
  VALIDATION_PHONE_INVALID = "VALIDATION_PHONE_INVALID",
  VALIDATION_REQUIRED_FIELD = "VALIDATION_REQUIRED_FIELD",
  VALIDATION_INVALID_FORMAT = "VALIDATION_INVALID_FORMAT",
  VALIDATION_MIN_LENGTH = "VALIDATION_MIN_LENGTH",
  VALIDATION_MAX_LENGTH = "VALIDATION_MAX_LENGTH",

  // Authentication errors (2000-2099)
  AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS",
  AUTH_ACCOUNT_NOT_VERIFIED = "AUTH_ACCOUNT_NOT_VERIFIED",
  AUTH_ACCOUNT_DISABLED = "AUTH_ACCOUNT_DISABLED",
  AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED",
  AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID",
  AUTH_UNAUTHORIZED = "AUTH_UNAUTHORIZED",
  AUTH_FORBIDDEN = "AUTH_FORBIDDEN",
  AUTH_2FA_REQUIRED = "AUTH_2FA_REQUIRED",
  AUTH_INVALID_2FA_CODE = "AUTH_INVALID_2FA_CODE",
  AUTH_ACCOUNT_CREATED = "AUTH_ACCOUNT_CREATED",
  AUTH_INVALID_TOKEN = "AUTH_INVALID_TOKEN",
  AUTH_INVALID_VERIFICATION_REQUEST = "AUTH_INVALID_VERIFICATION_REQUEST",
  AUTH_EMAIL_VERIFIED = "AUTH_EMAIL_VERIFIED",
  AUTH_TOKEN_REFRESHED = "AUTH_TOKEN_REFRESHED",
  AUTH_INVALID_REFRESH_TOKEN = "AUTH_INVALID_REFRESH_TOKEN",
  AUTH_2FA_NOT_SET_UP = "AUTH_2FA_NOT_SET_UP",
  AUTH_INVALID_2FA_TOKEN = "AUTH_INVALID_2FA_TOKEN",
  AUTH_2FA_ENABLED_SUCCESSFULLY = "AUTH_2FA_ENABLED_SUCCESSFULLY",
  AUTH_2FA_VERIFIED = "AUTH_2FA_VERIFIED",
  AUTH_2FA_NOT_ENABLED = "AUTH_2FA_NOT_ENABLED",
  AUTH_2FA_DISABLED_SUCCESSFULLY = "AUTH_2FA_DISABLED_SUCCESSFULLY",
  AUTH_SIGNUP_DISABLED = "AUTH_SIGNUP_DISABLED",

  // User errors (3000-3099)
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  FAILED_TO_CREATE_USER = "FAILED_TO_CREATE_USER",
  PASSWORD_REQUIRED_FOR_NEW_USER_REGISTRATION = "PASSWORD_REQUIRED_FOR_NEW_USER_REGISTRATION",
  USER_PROFILE_UPDATED_SUCCESSFULLY = "USER_PROFILE_UPDATED_SUCCESSFULLY",

  // Member errors (2100-2199)
  MEMBER_NOT_FOUND = "MEMBER_NOT_FOUND",
  MEMBER_CANNOT_CHANGE_OWN_ROLE = "MEMBER_CANNOT_CHANGE_OWN_ROLE",
  MEMBER_ONLY_OWNERS_CAN_ASSIGN_OWNER_ROLE = "MEMBER_ONLY_OWNERS_CAN_ASSIGN_OWNER_ROLE",
  MEMBER_REMOVED_SUCCESSFULLY = "MEMBER_REMOVED_SUCCESSFULLY",
  MEMBER_ROLE_UPDATED_SUCCESSFULLY = "MEMBER_ROLE_UPDATED_SUCCESSFULLY",
  MEMBER_CANNOT_REMOVE_YOURSELF = "MEMBER_CANNOT_REMOVE_YOURSELF",
  /** A member restricted to certain customers cannot grant full organization access to others */
  MEMBER_CANNOT_GRANT_FULL_ACCESS = "MEMBER_CANNOT_GRANT_FULL_ACCESS",
  /** Only organization owner can edit their own customer access */
  MEMBER_CANNOT_EDIT_OWN_ACCESS = "MEMBER_CANNOT_EDIT_OWN_ACCESS",
  MEMBER_CREATED_SUCCESSFULLY = "MEMBER_CREATED_SUCCESSFULLY",

  // Role errors (2200-2299)
  ROLE_NOT_FOUND = "ROLE_NOT_FOUND",
  ROLE_NAME_ALREADY_EXISTS = "ROLE_NAME_ALREADY_EXISTS",
  ROLE_SYSTEM_CANNOT_MODIFY = "ROLE_SYSTEM_CANNOT_MODIFY",
  ROLE_SYSTEM_CANNOT_DELETE = "ROLE_SYSTEM_CANNOT_DELETE",
  ROLE_IN_USE_CANNOT_DELETE = "ROLE_IN_USE_CANNOT_DELETE",
  ROLE_CREATED_SUCCESSFULLY = "ROLE_CREATED_SUCCESSFULLY",
  ROLE_UPDATED_SUCCESSFULLY = "ROLE_UPDATED_SUCCESSFULLY",
  ROLE_DELETED_SUCCESSFULLY = "ROLE_DELETED_SUCCESSFULLY",

  // Organization errors (4000-4099)
  ORGANIZATION_NOT_FOUND = "ORGANIZATION_NOT_FOUND",
  CUSTOMER_PARENT_REQUIRED = "CUSTOMER_PARENT_REQUIRED",
  VEHICLE_CUSTOMER_REQUIRED = "VEHICLE_CUSTOMER_REQUIRED",
  VEHICLE_NOT_FOUND = "VEHICLE_NOT_FOUND",

  // Driver errors (4100-4199)
  DRIVER_NOT_FOUND = "DRIVER_NOT_FOUND",
  DRIVER_ASSIGNMENT_NOT_FOUND = "DRIVER_ASSIGNMENT_NOT_FOUND",

  // Contact errors (5000-5099)
  CONTACT_NOT_FOUND = "CONTACT_NOT_FOUND",
  CONTACT_DUPLICATE_PHONE = "CONTACT_DUPLICATE_PHONE",
  CONTACT_DUPLICATE_EMAIL = "CONTACT_DUPLICATE_EMAIL",
  CONTACT_DELETED_SUCCESSFULLY = "CONTACT_DELETED_SUCCESSFULLY",
  CONTACT_PHONE_NUMBER_NOT_FOUND = "CONTACT_PHONE_NUMBER_NOT_FOUND",

  // Agent errors (6000-6099)
  AGENT_NOT_FOUND = "AGENT_NOT_FOUND",
  AGENT_NOT_ACTIVE = "AGENT_NOT_ACTIVE",
  AGENT_WEBHOOK_FAILED = "AGENT_WEBHOOK_FAILED",
  AGENT_INTENT_NOT_FOUND = "AGENT_INTENT_NOT_FOUND",
  AGENT_PROCESSING_FAILED = "AGENT_PROCESSING_FAILED",

  // MCP Server errors (6100-6199)
  MCP_SERVER_NOT_FOUND = "MCP_SERVER_NOT_FOUND",
  MCP_SERVER_GLOBAL_CANNOT_DELETE = "MCP_SERVER_GLOBAL_CANNOT_DELETE",

  // Message errors (7000-7099)
  MESSAGE_NOT_FOUND = "MESSAGE_NOT_FOUND",
  MESSAGE_FAILED_TO_SEND = "MESSAGE_FAILED_TO_SEND",
  MESSAGE_MEDIA_UPLOAD_FAILED = "MESSAGE_MEDIA_UPLOAD_FAILED",
  MESSAGE_INVALID_MEDIA_TYPE = "MESSAGE_INVALID_MEDIA_TYPE",
  MESSAGE_MEDIA_TOO_LARGE = "MESSAGE_MEDIA_TOO_LARGE",

  // WhatsApp errors (8000-8099)
  WHATSAPP_INSTANCE_NOT_FOUND = "WHATSAPP_INSTANCE_NOT_FOUND",
  WHATSAPP_CONNECTION_FAILED = "WHATSAPP_CONNECTION_FAILED",
  WHATSAPP_INVALID_MESSAGE_TYPE = "WHATSAPP_INVALID_MESSAGE_TYPE",
  WHATSAPP_CAN_ONLY_DELETE_MESSAGES_SENT_BY_YOU = "WHATSAPP_CAN_ONLY_DELETE_MESSAGES_SENT_BY_YOU",
  WHATSAPP_MESSAGE_ID_NOT_FOUND = "WHATSAPP_MESSAGE_ID_NOT_FOUND",
  WHATSAPP_MESSAGE_DELETED_FOR_EVERYONE = "WHATSAPP_MESSAGE_DELETED_FOR_EVERYONE",
  WHATSAPP_SERVICE_CONFIG_MISSING = "WHATSAPP_SERVICE_CONFIG_MISSING",
  WHATSAPP_INSTANCE_UPDATED_SUCCESSFULLY = "WHATSAPP_INSTANCE_UPDATED_SUCCESSFULLY",

  // Instagram errors (8100-8199)
  INSTAGRAM_ACCOUNT_ALREADY_CONNECTED = "INSTAGRAM_ACCOUNT_ALREADY_CONNECTED",
  INSTAGRAM_ACCOUNT_DISCONNECTED = "INSTAGRAM_ACCOUNT_DISCONNECTED",
  INSTAGRAM_CONVERSATION_NOT_INITIATED = "INSTAGRAM_CONVERSATION_NOT_INITIATED",

  // File errors (9000-9099)
  FILE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED",
  FILE_INVALID_FILE_TYPE = "FILE_INVALID_FILE_TYPE",
  FILE_TOO_LARGE = "FILE_TOO_LARGE",
  FILE_NOT_FOUND = "FILE_NOT_FOUND",

  // Knowledge Base errors (9100-9199)
  KNOWLEDGE_BASE_FILE_LIMIT_REACHED = "KNOWLEDGE_BASE_FILE_LIMIT_REACHED",
  KNOWLEDGE_BASE_INVALID_FILE_TYPE = "KNOWLEDGE_BASE_INVALID_FILE_TYPE",
  KNOWLEDGE_BASE_FILE_TOO_LARGE = "KNOWLEDGE_BASE_FILE_TOO_LARGE",
  KNOWLEDGE_BASE_FILE_PROCESSING = "KNOWLEDGE_BASE_FILE_PROCESSING",

  // Common errors (10000+)
  COMMON_INTERNAL_SERVER_ERROR = "COMMON_INTERNAL_SERVER_ERROR",
  COMMON_BAD_REQUEST = "COMMON_BAD_REQUEST",
  COMMON_NOT_FOUND = "COMMON_NOT_FOUND",
  COMMON_INVALID_INPUT = "COMMON_INVALID_INPUT",
  COMMON_ACCESS_DENIED = "COMMON_ACCESS_DENIED",
  COMMON_RATE_LIMIT_EXCEEDED = "COMMON_RATE_LIMIT_EXCEEDED",
  COMMON_MAINTENANCE_MODE = "COMMON_MAINTENANCE_MODE",
  COMMON_ALREADY_EXISTS = "COMMON_ALREADY_EXISTS",
}
